add missing <unistd.h>
Fixes compile error with gcc 14:
```text
glibc_2.23/mmap_overlapping_chunks.c: In function ‘main’:
glibc_2.23/mmap_overlapping_chunks.c:142:9: error: implicit declaration of function ‘_exit’; did you mean ‘_Exit’? [-Wimplicit-function-declaration]
  142 |         _exit(0); // exit early just in case we corrupted some libraries
      |         ^~~~~
      |         _Exit
```